name: Build and Publish Production Image

on:
  push:
    branches: [main]  # ou ajuste conforme necessário

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build imagem de produção
        run: |
          docker build \
            --target production \
            -t ghcr.io/${{ github.repository_owner }}/chirper:latest .

      - name: Push imagem para GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/chirper:latest
